### ISSUE TITLE
Align misaligned center button on mobile for /status

### ISSUE THREAD

**Issue by SaltyQuetzals** [tamuhack-org/Ouroboros#85]
**Describe the Bug**
When using Responsive Design Mode (browser emulation of mobile device viewports), the button in the center is aligned too far to the right, rather than to the left.

**To Reproduce**
1. Using Firefox/Chrome
2. Perform the processes required to get to the "Submitted" screen

**Screenshots**
![Firefox](https://user-images.githubusercontent.com/15918436/60541364-4bc26700-9cc6-11e9-8bdd-66dd6a588a14.png)
![Chrome (iPhone X)](https://user-images.githubusercontent.com/15918436/60541400-672d7200-9cc6-11e9-8bca-556de08de566.png)

**Additional context**
iPhone X is used, but I anticipate any device with a small-enough viewport will perform similarly

**Comment by gracekfan** [comment]
i think this has been fixed unless it's only on the view application button

**Comment by gracekfan** [comment]
<img width="361" alt="Screen Shot 2019-07-08 at 10 37 11 PM" src="https://user-images.githubusercontent.com/33182506/60857650-f4922a00-a1d0-11e9-893d-c8e59d8209f4.png">
galaxy s5

**Comment by gracekfan** [comment]
should be fixed if we reduce l/r padding on .login class on mobile

**Comment by jonathan-innis** [comment]
Fixed

**Comment by gracekfan** [comment]
<img width="394" alt="Screen Shot 2019-07-17 at 8 01 13 PM" src="https://user-images.githubusercontent.com/33182506/61421669-afa37d00-a8cd-11e9-8a21-1b776cfe67e5.png">
this not fixed (shown iphone 6/7)
